### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by KamilGPSEA** [Mairie-de-Saint-Maur/AppMonitor#2]
Bonjour, 
Je sollicite une fois de plus votre aide, 
En effet lorsque j'entre une maintenance en dur dans applis.conf, plus aucun logiciel s'affiche sur ma page.

**Comment by camuzic** [comment]
Il n'y a pas de fichier "applis.conf" dans AppMonitor.
Il se trouve dans l'autre projet : https://github.com/Mairie-de-Saint-Maur/ListApp
Merci d'ouvrir une issue là bas si vous avez un problème technique de type bug.
Sinon, joignez-moi par téléphone. Merci.
